### ISSUE TITLE
Error while running python caravel_reram_test.py -t sky130 -v

### ISSUE THREAD

**Issue by Samarthjainabout** [lekez2005/opennvram-reram#3]
File "/home/staff/elesamj/sky130a/opennvram-reram-main/compiler/options.py", line 207, in set_temp_folder
    default_openram_temp = os.path.join(os.environ['SCRATCH'], 'openram')
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'SCRATCH'

Does anyone know how to set scratch variable?

**Comment by lekez2005** [comment]
This was a bug which is now fixed with the latest commit. You can update to get the latest changes. For your reference, you can set environment variables using `export SCRATCH=<insert_path_here>` if using bash or zsh; `setenv SCRATCH  <insert_path_here>` on tcsh. 
I suspect there will be additional setup-related bugs so feel free to open additional issues or just continue on this issue until you get it working.
